package inventory.model;
// Generated 20-may-2017 0:21:57 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Measurement generated by hbm2java
 */
@Entity
@Table(name="measurement"
    ,catalog="kaizenso_inventory"
    , uniqueConstraints = {@UniqueConstraint(columnNames="name"), @UniqueConstraint(columnNames="abbreviation")} 
)
public class Measurement  implements java.io.Serializable {


     private Integer id;
     private String name;
     private String abbreviation;

    public Measurement() {
    }

    public Measurement(String name, String abbreviation) {
       this.name = name;
       this.abbreviation = abbreviation;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="name", unique=true, nullable=false)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="abbreviation", unique=true, nullable=false)
    public String getAbbreviation() {
        return this.abbreviation;
    }
    
    public void setAbbreviation(String abbreviation) {
        this.abbreviation = abbreviation;
    }




}


